# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Compile

on:
  push:
    branches: ["bulma"]
  pull_request:
    branches: ["bulma"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        # uses: denoland/setup-deno@v2
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb  # v1.1.2

      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick

      - name: Build site
        run: deno task build

      - name: Upload artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          path: ./build

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4.0.5
