# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Compile

on:
  push:
    branches: ["bulma"]
    paths:
      - ".github/workflows/*.yml"
      - "bin/**/*"
      - "src/**/*"
      - "config/**/*"
      - "img/**/*"
      - "js/**/*"
      - "style/**/*"
      - "template/**/*"
      - "deno.json"
      - "deno.lock"
      - "Brewfile"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DENO_DIR: ${{ github.workspace }}/.deno_cache

    steps:
      - name: Prepare env
        run: |
          echo "BUILD_ENV=GH_PAGES" >> $GITHUB_ENV

      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Homebrew
        id: set-up-homebrew
        run: |
          echo "/home/linuxbrew/.linuxbrew/bin"  >> $GITHUB_PATH
          echo "/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

      - name: Install Homebrew dependencies
        id: install-homebrew-dependencies
        run: |
          brew bundle install

      - name: Restore Deno cache
        uses: actions/cache/restore@v5
        id: cache-deno
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock', 'deno.json') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Install Deno dependencies
        if: ${{ steps.cache-deno.outputs.cache-hit != 'true' }}
        run: |
          deno install

      - name: Save Deno cache
        if: ${{ steps.cache-deno.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v5
        with:
          path: ${{ env.DENO_DIR }}
          key: ${{ runner.os }}-deno-${{ hashFiles('deno.lock', 'deno.json') }}

      - name: Build site
        run: |
          deno task build

      - name: Upload artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    needs: build

    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4.0.5
